### ISSUE TITLE
"scrollToPage" NOT working!!!

### ISSUE THREAD

**Issue by andre-r-gomes** [torinnguyen/PepperUIDemoFree#2]
I bought the library for $200 and its still very buggy... Im content with that, as no code is perfect. I cant for the life of me figure out why the scrollToPage method wont work.

Could you list possible reasons?

**Comment by torinnguyen** [comment]
HI Andre,

Thank you for purchasing the full license for PepperUI.
You are entitled to 1 year support from me. This includes any bug fixes & updates.

I'll check out the scrollToPage method and get back to you soon.
This is the first time I've issues in this particular method.

Meanwhile, please do file a bug on BinPress so that I can keep you and others updated easily.

Torin  

## 

Torin Nguyen
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by torinnguyen** [comment]
Hi Andre,

I've just checkout my library and realise that scrollToPage function was only designed for fullscreen Scroll effect. It won't work in any other mode.

I have just added a function flipToPage for the 3D/Pepper mode so you can flip to any page you want in 3D/Pepper mode. Will be releasing this new version soon.

Where else do need this kind of feature?
Let me know soon so that I can add it to the next release too.

Torin   

## 

Torin Nguyen
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by andre-r-gomes** [comment]
Fantastic!!

How soon will I be able to get the updated version, as I have a deadline in the next 2 days and I used your library to make a prototype...

If possible, could you give me the code snippet so I can Implement it?

That's the only issue I have with your library, otherwise, all good :)

**Comment by torinnguyen** [comment]
Hi,  

I have already updated my code 2 days ago.
It's version 1.4.7 on BinPress.
You should have gotten an email notification about the update.

Let me know if you have trouble getting the new source code.

## 

Torin Nguyen
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
